spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_db?&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jaeil
    password: jaeil

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernates:
        ddl-auto: update
---
jwt :
  headers: Authorization
  secretKey: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  expiration: 9600000
